spring:
  application:
    name: priority-reminder-system

  datasource:
    url: jdbc:postgresql://localhost:5432/reminderdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#   jackson:
#     time-zone: Asia/Kolkata
server:
  port: 8080
